# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pochhammer <- function(a_real, a_imag, q_real, q_imag, n, maxit) {
    .Call(`_queueR_pochhammer`, a_real, a_imag, q_real, q_imag, n, maxit)
}

qexp_C <- function(z_real, z_imag, q_real, q_imag, maxit) {
    .Call(`_queueR_qexp_C`, z_real, z_imag, q_real, q_imag, maxit)
}

BasicHypergeometric <- function(z_real, z_imag, q_real, q_imag, a_real, a_imag, b_real, b_imag, maxit) {
    .Call(`_queueR_BasicHypergeometric`, z_real, z_imag, q_real, q_imag, a_real, a_imag, b_real, b_imag, maxit)
}

