# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

complex_multiply <- function(a_real, a_imag, q_real, q_imag) {
    .Call(`_queueR_complex_multiply`, a_real, a_imag, q_real, q_imag)
}

